[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build && cp public/_redirects build/_redirects"

[deploy]
startCommand = "node server.js"
restartPolicyType = "on_failure"

[env]
REACT_APP_API_BASE_URL = "https://faroukmanager-backend-production-feb9.up.railway.app/api"
REACT_APP_ENV = "production"
